version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ksg9482/fastapi-post:24.09.04
    ports:
      - "80:8000" 
    depends_on:
      - db
      - db2
      - redis
      - redis2
      - redis3
    networks:
      - app-network
    environment:
      - DATABASE_URL=mysql+aiomysql://user:password@db:3306/exampledb
      - REDIS_URL=redis://localhost
      - PYTHONPATH="./"
      - LOCAL_UPLOAD_DIR="./profile_img"
      - REQUESTS_PER_MINUTE=60
      - BUCKET_SIZE=10.0
      - GOOGLE_APPLICATION_CREDENTIALS="./keys/gcp_private_key.json"
      - GCP_PRIVATE_KEY_BASE64=""
      - GCP_STORAGE_URL="https://storage.googleapis.com"
      - GCP_BUCKET_NAME="fastapi-post-storage"

  db:
    image: mysql:lts 
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'exampledb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - app-network
      
  db2:
    image: mysql:lts 
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'exampledb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  redis2:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - app-network

  redis3:
    image: redis:alpine
    ports:
      - "6381:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldata:
