version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    image: fastapi-post:0.1
    ports:
      - "8000:8000" 
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/exampledb 

  db:
    image: mysql:lts 
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'exampledb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldata:

# docker-compose up --build